// web/src/Landing.vue
<template>
  <div style="background-image: url(https://upload.wikimedia.org/wikipedia/commons/6/6f/%C3%87atalh%C3%B6y%C3%BCk_after_the_first_excavations_by_James_Mellaart_and_his_team..jpg); background-size: 100% 100%; height: 100%">
    <v-layout row justify-end class="ma-3">
      <v-btn v-on:click="login" color="indigo">Login</v-btn>
    </v-layout>
    <v-layout row align-center justify-center>
      <h2 class="display-4 font-weight-black" style="margin-top: 200px">charcoal</h2>
    </v-layout>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class Landing extends Vue {
  login() {
    this.$auth.login();
  }
}
</script>

// charcoal/src/home/Landing.tsx
import React, { Component } from 'react';
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
import { Button } from '@material-ui/core';
import { connect } from 'react-redux';
import { AppState } from '../store';
import { login } from '../auth/store/thunks';

const backgroundStyle = {
  position: 'fixed' as 'fixed',
  backgroundImage: 'url(https://upload.wikimedia.org/wikipedia/commons/6/6f/%C3%87atalh%C3%B6y%C3%BCk_after_the_first_excavations_by_James_Mellaart_and_his_team..jpg)',
  backgroundSize: 'cover',
  height: '100%',
  width: '100%'
};

export class Landing extends Component<Props> {
  render() {
    return (
      <div>
        <div style={backgroundStyle} >
          <Grid container justify="flex-end">
            <Grid item xs={1}>
              <Typography align="right" style={{ margin: "20px" }}>
                <Button variant="contained" color="primary" onClick={this.props.login}>Login</Button>
              </Typography>
            </Grid>
          </Grid>
          <Grid container justify="center">
            <h1 className="" style={{ marginTop: '200px' }}>charcoal</h1>
          </Grid>
        </div>
      </div>
    );
  }
}

interface DispatchProps {
  login: () => void;
}

type Props = DispatchProps;

export default connect<{}, DispatchProps, {}, AppState>(
  null,
  { login: login }
)(Landing);
